name: codespell
on:
  push:
    branches: [ main ]
    paths: '**.py'
  pull_request:
    branches: [ main ]
    paths: '**.py'
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: codespell --ignore-words-list="ans,nnumber,nin" --quiet-level=2  # --skip=""
