name: golangci-lint
on:
  push:
    branches: [ main ]
    paths: '**.go'
  pull_request:
    branches: [ main ]
    paths: '**.go'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: algorithms/Go

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
      - run: go test $(go list ./... | grep -v /sbom | grep -v /rsa)
